name: infer-net-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install black

      - name: Run linter with ruff
        run: ruff check .

      - name: Run formatter with black
        run: black --check .

test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download Model Artifact
        run: |
          mkdir -p artifacts
          curl -L -o artifacts/infer-net.keras "https://github.com/zhu-weijie/infer-net/releases/download/v1.0.0-model/infer-net.keras"

      - name: Run tests with pytest
        run: pytest

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Model Artifact
        run: |
          mkdir -p artifacts
          curl -L -o artifacts/infer-net.keras "https://github.com/zhu-weijie/infer-net/releases/download/v1.0.0-model/infer-net.keras"

      - name: Build Docker image
        run: docker build . --tag infer-net:latest
